import google from '../../assets/google.png'
import google from '../../assets/slack.png'
import google from '../../assets/atlassian.png'
import google from '../../assets/dropp.png'
import google from '../../assets/google.png'